USE [Test-Database]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ACTORS](
	[AID] [int] NOT NULL,
	[NAME] [varchar](max) NOT NULL,
	[GENDER] [datetime] NOT NULL,
	[AGE] [datetime] NOT NULL,
 CONSTRAINT [PK_ACTORS] PRIMARY KEY CLUSTERED 
(
	[AID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

