USE [Test-Database]
GO

/****** Object:  Table [dbo].[TVSHOWS]    Script Date: 3/13/2019 3:04:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TVSHOWS](
	[TID] [int] NOT NULL,
	[TNAME] [varchar](max) NOT NULL,
	[DATEOFRELEASE] [datetime] NOT NULL,
	[GENRE] [varchar](50) NOT NULL,
	[DURATION] [time](7) NOT NULL,
 CONSTRAINT [PK_TVSHOWS] PRIMARY KEY CLUSTERED 
(
	[TID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

