USE [Test-Database]
GO

/****** Object:  Table [dbo].[WORKSONTV]    Script Date: 3/13/2019 3:04:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WORKSONTV](
	[AID] [int] NOT NULL,
	[TID] [int] NOT NULL,
	[NOOFSHOWS] [int] NOT NULL,
	[NOOFDAYS] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WORKSONTV]  WITH CHECK ADD  CONSTRAINT [FK_WORKSONTV_ACTORS] FOREIGN KEY([AID])
REFERENCES [dbo].[ACTORS] ([AID])
GO

ALTER TABLE [dbo].[WORKSONTV] CHECK CONSTRAINT [FK_WORKSONTV_ACTORS]
GO

ALTER TABLE [dbo].[WORKSONTV]  WITH CHECK ADD  CONSTRAINT [FK_WORKSONTV_TVSHOWS] FOREIGN KEY([TID])
REFERENCES [dbo].[TVSHOWS] ([TID])
GO

ALTER TABLE [dbo].[WORKSONTV] CHECK CONSTRAINT [FK_WORKSONTV_TVSHOWS]
GO

